title = "bellecv title"
baseURL = "https://BelleCV.github.io/" 
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Home"
  
  [menu]

    [[menu.header]]
      weight = 2
      name = "Service"
      url = "/service"
    [[menu.header]]
      weight = 3
      name = "Belle's Blog"
      url = "/blog"
    [[menu.header]]
      weight = 4
      name = "Customers' Feedback"
      url = "/service"
    [[menu.header]]
      weight = 5
      name = "Contact"
      url = "/contact"

    [[menu.footer]]
      weight = 1
      name = "About us"
      url = "#"
    [[menu.footer]]
      weight = 2
      name = "Contact us"
      url = "#"
    [[menu.footer]]
      weight = 3
      name = "How it works"
      url = "#"
    [[menu.footer]]
      weight = 4
      name = "Blog"
      url = "#"
    [[menu.footer]]
      weight = 5
      name = "Terms"
      url = "#"

  [params.slider]
    enable = true
    title = "貝兒簡歷 <br> Belle CV Consulting"
    subtitle = "深入瞭解您的需求<br>最個人化的簡歷編輯服務<br>每一份簡歷，都是一位客戶的精彩生命故事！"
    bgImage = "img/starynight.jpg"
    btnText = "看更多我們的服務 <3"
    url = "#"

  [params.wrapper]
    enable = true
    image = "img/london.jpg"
    title = "What we offered"
    italic = "貝兒簡歷顧問   提供個人化的簡歷/自傳撰寫、修編、翻譯、面試諮詢等服務"
    paragraph = "找工作、走學術，</br><br><br />想讓您的簡歷/自傳更完美，<br>突出個人專業、專精和歷來成就，<br>擁有符合職位的排版與風格，使面試官一目瞭然——<br>貝兒簡歷，提供想讓簡歷更好的您們，最符合個人需求的服務！&#09在貝兒，我們相信，每份簡歷都代表著一位活生生的人們tab2我們希望客戶們能藉由簡歷，呈現出space4tab6最好的自己"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = ""
    bgImage = "img/ibelieve.jpg"
    content = "在貝兒，我們相信，每份簡歷都代表著一位活生生的人們2tabs我們希望客戶們能藉由簡歷，呈現出4spaces6tabs最好的自己"
    #[params.feature.button]
    #  caption = "View Works"
    #  url = "#"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "Contact Belle,"
    paragraph = "email: SendUrCVtoBelle@gmail.com<br>任何需求、問題<br>都歡迎和我們聯繫<br>Belle CV Consulting, 期待您的來信"

    #[params.call.button]
    #  url = "https://www.businessweekly.com.tw/article.aspx?id=11255&type=Blog"
    #  text = "yeah"
