title = "bellecv title"
baseURL = "https://BelleCV.github.io/" 
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Home"
  
  [menu]

    [[menu.header]]
      weight = 2
      name = "Work"
      url = "/work"
    [[menu.header]]
      weight = 3
      name = "Blog"
      url = "/blog"
    [[menu.header]]
      weight = 4
      name = "Service"
      url = "/service"
    [[menu.header]]
      weight = 5
      name = "Contact"
      url = "/contact"

    [[menu.footer]]
      weight = 1
      name = "About us"
      url = "#"
    [[menu.footer]]
      weight = 2
      name = "Contact us"
      url = "#"
    [[menu.footer]]
      weight = 3
      name = "How it works"
      url = "#"
    [[menu.footer]]
      weight = 4
      name = "Blog"
      url = "#"
    [[menu.footer]]
      weight = 5
      name = "Terms"
      url = "#"

  [params.slider]
    enable = true
    title = "A game changing <br> resume design"
    subtitle = "I want you to seize the chance toward your unlimited future."
    bgImage = "img/starynight.jpg"
    btnText = "Discover Our Projects"
    url = "#"

  [params.wrapper]
    enable = true
    image = "img/london.jpg"
    title = "About Me"
    italic = "Please do not have any bias before you have full picture about any topic."
    paragraph = "I am a free lencer who is enthusiastic at career consulting."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "I believe in you"
    bgImage = "img/ibelieve.jpg"
    content = "You can do this."
    #[params.feature.button]
    #  caption = "View Works"
    #  url = "#"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "North Main Street, Brooklyn Australia"
      email = "Email: contact@mail.com"
      phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "I am looking forward that you reach out to me."
    paragraph = "email: sendurcvtobelle@gmail.com"
    [params.call.button]
      url = "https://www.businessweekly.com.tw/article.aspx?id=11255&type=Blog"
      text = "yeah"
